default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: novakj
  password: password  # if you set one
  host: localhost

development:
  <<: *default
  database: landix_development

test:
  <<: *default
  database: landix_test

production:
  <<: *default
  database: landix_production
  username: landix
  password: <%= ENV["LANDIX_DATABASE_PASSWORD"] %>
